version: '3'

services:

  tims-app:
    build:
      context: .
    container_name: tims-app
    ports:
      - "80:8080"
    networks:
      - tims_network
    volumes:
      - .:/var/www/tims

networks:
  tims_network:
    name: tims_network
    driver: bridge